# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Guiaom2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Guiaom import Ui_Guiaom
class Ui_Guiaom2(object):
    def opanwindowVND(self):
        self.window1 = QtWidgets.QMainWindow()
        self.num = float(0.001305)
        self.ui = Ui_Guiaom(self.num)
        self.ui.setupUi(self.window1)
        self.window1.show()

    def opanwindowIDR(self):
        self.window1 = QtWidgets.QMainWindow()
        self.num = float(0.002135)
        self.ui = Ui_Guiaom(self.num)
        self.ui.setupUi(self.window1)
        self.window1.show()
    def opanwindowMMK(self):
        self.window1 = QtWidgets.QMainWindow()
        self.num = float(0.02283)
        self.ui = Ui_Guiaom(self.num)
        self.ui.setupUi(self.window1)
        self.window1.show()
    def opanwindowPHP(self):
        self.window1 = QtWidgets.QMainWindow()
        self.num = float(0.62815)
        self.ui = Ui_Guiaom(self.num)
        self.ui.setupUi(self.window1)
        self.window1.show()

    def opanwindowKHR(self):
        self.window1 = QtWidgets.QMainWindow()
        self.num = 0.007456
        self.ui = Ui_Guiaom(self.num)
        self.ui.setupUi(self.window1)
        self.window1.show()

    def opanwindowLAK(self):
        self.window1 = QtWidgets.QMainWindow()
        self.num = 0.003256
        self.ui = Ui_Guiaom(self.num)
        self.ui.setupUi(self.window1)
        self.window1.show()

    def opanwindowMYR(self):
        self.window1 = QtWidgets.QMainWindow()
        self.num = 7.4090
        self.ui = Ui_Guiaom(self.num)
        self.ui.setupUi(self.window1)
        self.window1.show()

    def opanwindowBND(self):
        self.window1 = QtWidgets.QMainWindow()
        self.num = 22.5913
        self.ui = Ui_Guiaom(self.num)
        self.ui.setupUi(self.window1)
        self.window1.show()

    def opanwindowSGD(self):
        self.window1 = QtWidgets.QMainWindow()
        self.num = 22.6210
        self.ui = Ui_Guiaom(self.num)
        self.ui.setupUi(self.window1)
        self.window1.show()

    def opanwindowUSD(self):
        self.window1 = QtWidgets.QMainWindow()
        self.num = 30.1949
        self.ui = Ui_Guiaom(self.num)
        self.ui.setupUi(self.window1)
        self.window1.show()

    def h1(self,Guiaom2):
        Guiaom2.hide()
    def setupUi(self, Guiaom2):
        Guiaom2.setObjectName("Guiaom2")
        Guiaom2.resize(800, 600)
        Guiaom2.setMaximumSize(QtCore.QSize(800, 600))
        Guiaom2.setStyleSheet("background-image: url(:/A2/141894_00_2x.jpg);\n"
"")
        self.centralwidget = QtWidgets.QWidget(Guiaom2)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 90, 291, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_6.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_6.setStyleSheet("background-image: url(:/A2/abstract-halftone-background_23-2148583453.jpg);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.clicked.connect(self.opanwindowVND)
        self.pushButton_6.clicked.connect(lambda: self.h1(Guiaom2))
        self.verticalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_7.setStyleSheet("background-image: url(:/A2/abstract-halftone-background_23-2148583453.jpg);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.clicked.connect(self.opanwindowIDR)
        self.pushButton_7.clicked.connect(lambda: self.h1(Guiaom2))
        self.verticalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_5.setStyleSheet("background-image: url(:/A2/abstract-halftone-background_23-2148583453.jpg);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.opanwindowMMK)
        self.pushButton_5.clicked.connect(lambda: self.h1(Guiaom2))
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_2.setStyleSheet("background-image: url(:/A2/abstract-halftone-background_23-2148583453.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.opanwindowPHP)
        self.pushButton_2.clicked.connect(lambda: self.h1(Guiaom2))
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_4.setStyleSheet("background-image: url(:/A2/abstract-halftone-background_23-2148583453.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.opanwindowKHR)
        self.pushButton_4.clicked.connect(lambda: self.h1(Guiaom2))
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(440, 90, 291, 401))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_8.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_8.setStyleSheet("background-image: url(:/A2/abstract-halftone-background_23-2148583453.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.clicked.connect(self.opanwindowLAK)
        self.pushButton_8.clicked.connect(lambda: self.h1(Guiaom2))
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_9.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_9.setStyleSheet("background-image: url(:/A2/abstract-halftone-background_23-2148583453.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.clicked.connect(self.opanwindowMYR)
        self.pushButton_9.clicked.connect(lambda: self.h1(Guiaom2))
        self.verticalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_10.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_10.setStyleSheet("background-image: url(:/A2/abstract-halftone-background_23-2148583453.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.clicked.connect(self.opanwindowBND)
        self.pushButton_10.clicked.connect(lambda: self.h1(Guiaom2))
        self.verticalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_3.setStyleSheet("background-image: url(:/A2/abstract-halftone-background_23-2148583453.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.opanwindowSGD)
        self.pushButton_3.clicked.connect(lambda: self.h1(Guiaom2))
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.pushButton_11 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_11.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pushButton_11.setStyleSheet("background-image: url(:/A2/abstract-halftone-background_23-2148583453.jpg);\n"
"font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.clicked.connect(self.opanwindowUSD)
        self.pushButton_11.clicked.connect(lambda: self.h1(Guiaom2))
        self.verticalLayout_3.addWidget(self.pushButton_11)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 331, 71))
        self.label.setStyleSheet("background-image: url(:/A2/abstract-halftone-background_23-2148583453.jpg);\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"MS Shell Dlg 2\";")
        Guiaom2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Guiaom2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Guiaom2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Guiaom2)
        self.statusbar.setObjectName("statusbar")
        Guiaom2.setStatusBar(self.statusbar)

        self.retranslateUi(Guiaom2)
        QtCore.QMetaObject.connectSlotsByName(Guiaom2)

    def retranslateUi(self, Guiaom2):
        _translate = QtCore.QCoreApplication.translate
        Guiaom2.setWindowTitle(_translate("Guiaom2", "Currency exchange program"))
        self.pushButton_6.setText(_translate("Guiaom2", "Vietnam(VND)"))
        self.pushButton_7.setText(_translate("Guiaom2", "Indonesia(IDR)"))
        self.pushButton_5.setText(_translate("Guiaom2", "Myanmar(MMK)"))
        self.pushButton_2.setText(_translate("Guiaom2", "Philippines(PHP)"))
        self.pushButton_4.setText(_translate("Guiaom2", "Cambodia(KHR)"))
        self.pushButton_8.setText(_translate("Guiaom2", "Laos(LAK)"))
        self.pushButton_9.setText(_translate("Guiaom2", "Malaysia(MYR)"))
        self.pushButton_10.setText(_translate("Guiaom2", "Brunei Darussalam(BND)"))
        self.pushButton_3.setText(_translate("Guiaom2", "Singapore(SGD)"))
        self.pushButton_11.setText(_translate("Guiaom2", "Dollar(USD)"))
        self.label.setText(_translate("Guiaom2", " Choose your currency"))
import imaom2_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Guiaom2 = QtWidgets.QMainWindow()
    ui = Ui_Guiaom2()
    ui.setupUi(Guiaom2)
    Guiaom2.show()
    sys.exit(app.exec_())
