# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Guiaom3.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import imaom3_rc
from PyQt5 import QtCore, QtGui, QtWidgets
from Guiaom2 import Ui_Guiaom2


class Ui_Guiaom3(object):
    def opanwindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Guiaom2()
        self.ui.setupUi(self.window)
        Guiaom3.hide()
        self.window.show()

    def setupUi(self, Guiaom3):
        Guiaom3.setObjectName("Guiaom3")
        Guiaom3.resize(800, 600)
        Guiaom3.setStyleSheet("background-image: url(:/A3/141894_00_2x.jpg);")
        self.centralwidget = QtWidgets.QWidget(Guiaom3)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(190, 60, 461, 351))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 400))
        self.label.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";\n"
                                 "background-color: rgb(170, 0, 255);\n"
                                 "font: 75 22pt \"MS Shell Dlg 2\";\n"
                                 "border-image: url(:/A3/abstract-halftone-background_23-2148583453.jpg);\n"
                                 "color: rgb(170, 0, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pnt_onpen = QtWidgets.QPushButton(self.widget)
        self.pnt_onpen.setMaximumSize(QtCore.QSize(16777215, 60))
        self.pnt_onpen.setStyleSheet("background-image: url(:/A3/1876a4e9d6b9ba091d2516b3eab92db7.jpg);\n"
                                     "color: rgb(170, 0, 255);\n"
                                     "background-color: rgb(170, 0, 255);\n"
                                     "font: 18pt \"MS Shell Dlg 2\";")
        self.pnt_onpen.setObjectName("pnt_onpen")

        self.pnt_onpen.clicked.connect(self.opanwindow)

        self.verticalLayout.addWidget(self.pnt_onpen)
        Guiaom3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Guiaom3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 26))
        self.menubar.setObjectName("menubar")
        Guiaom3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Guiaom3)
        self.statusbar.setObjectName("statusbar")
        Guiaom3.setStatusBar(self.statusbar)

        self.retranslateUi(Guiaom3)
        QtCore.QMetaObject.connectSlotsByName(Guiaom3)

    def retranslateUi(self, Guiaom3):
        _translate = QtCore.QCoreApplication.translate
        Guiaom3.setWindowTitle(_translate(
            "Guiaom3", "Currency exchange program"))
        self.label.setText(_translate("Guiaom3", "      Currency exchange"))
        self.pnt_onpen.setText(_translate("Guiaom3", "open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Guiaom3 = QtWidgets.QMainWindow()
    ui = Ui_Guiaom3()
    ui.setupUi(Guiaom3)
    Guiaom3.show()
    sys.exit(app.exec_())
